spring:
  application:
    name: event-sourcing-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.88:3306/event?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson